In [5]:
pip install scikit-learn


     ---------------------------------------- 0.0/60.8 kB ? eta -:--:--
     ---------------------------------------- 60.8/60.8 kB 3.2 MB/s eta 0:00:00
  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
  Using cached threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.1 MB 15.0 MB/s eta 0:00:01
   --- ------------------------------------ 1.0/11.1 MB 12.2 MB/s eta 0:00:01
   ----- ---------------------------------- 1.5/11.1 MB 10.5 MB/s eta 0:00:01
   ------- -------------------------------- 2.0/11.1 MB 11.7 MB/s eta 0:00:01
   --------- ------------------------------ 2.7/11.1 MB 11.2 MB/s eta 0:00:01
   ----------- ---------------------------- 3.1/11.1 MB 11.1 MB/s eta 0:00:01
   ------------- -------------------------- 3.6/11.1 MB 11.1 MB/s eta 0:00:01
   --------------- ------------------------ 4.2/11.1 MB 11.2 MB/s eta 0:00:01
   ---------------- -


[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [37]:
pip install imbalanced-learn

   ---------------------------------------- 0.0/238.4 kB ? eta -:--:--
   --------------------------------------  235.5/238.4 kB 14.1 MB/s eta 0:00:01
   ---------------------------------------- 238.4/238.4 kB 7.4 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
pip install pandas


   ---------------------------------------- 0.0/11.6 MB ? eta -:--:--
   - -------------------------------------- 0.4/11.6 MB 11.2 MB/s eta 0:00:02
   -- ------------------------------------- 0.8/11.6 MB 10.2 MB/s eta 0:00:02
   ---- ----------------------------------- 1.3/11.6 MB 10.5 MB/s eta 0:00:01
   ------ --------------------------------- 1.8/11.6 MB 10.2 MB/s eta 0:00:01
   ------- -------------------------------- 2.1/11.6 MB 10.2 MB/s eta 0:00:01
   ------- -------------------------------- 2.1/11.6 MB 10.2 MB/s eta 0:00:01
   -------- ------------------------------- 2.4/11.6 MB 7.6 MB/s eta 0:00:02
   ---------- ----------------------------- 2.9/11.6 MB 8.2 MB/s eta 0:00:02
   ----------- ---------------------------- 3.3/11.6 MB 8.2 MB/s eta 0:00:02
   ------------- -------------------------- 3.8/11.6 MB 8.5 MB/s eta 0:00:01
   -------------- ------------------------- 4.3/11.6 MB 8.6 MB/s eta 0:00:01
   ---------------- ----------------------- 4.8/11.6 MB 8.8 MB/s eta 0:00:01


[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
print("hello world")

hello world


In [1]:
import numpy as np
import pandas as pd
from imblearn.under_sampling import TomekLinks
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import svm
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix

In [2]:
diabetes_dataset=pd.read_csv("../datasets/diabetes.csv")

In [9]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
diabetes_dataset.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [4]:
diabetes_dataset.shape

(768, 9)

In [5]:
diabetes_dataset.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [6]:
diabetes_dataset['Outcome']

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [12]:
diabetes_dataset['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [13]:
diabetes_dataset.groupby('Outcome').mean()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
Outcome                                                                      
0           3.298000  109.980000      68.184000      19.664000   68.792000   
1           4.865672  141.257463      70.824627      22.164179  100.335821   

               BMI  DiabetesPedigreeFunction        Age  
Outcome                                                  
0        30.304200                  0.429734  31.190000  
1        35.142537                  0.550500  37.067164

In [8]:
x=diabetes_dataset.drop(columns=['Outcome'],axis=1)
y=diabetes_dataset['Outcome']

In [15]:
x.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31  
2                     0.672   32  
3                     0.167   21  
4                     2.288   33

In [9]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [21]:
# Initialize Tomek Links
tomek = TomekLinks()

# Apply Tomek Links undersampling to remove unnecessary majority class points
X_resampled, y_resampled = tomek.fit_resample(x_train, y_train)

# Print class distribution before and after undersampling
print("Original class distribution:\n", y_train.value_counts())
print("\nClass distribution after Tomek Links:\n", pd.Series(y_resampled).value_counts())

Original class distribution:
 Outcome
0    401
1    213
Name: count, dtype: int64

Class distribution after Tomek Links:
 Outcome
0    366
1    213
Name: count, dtype: int64


In [11]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [12]:
x_train.shape

(614, 8)

In [13]:
x_test.shape

(154, 8)

In [14]:
y_train.head()

60     0
618    1
346    0
294    0
231    1
Name: Outcome, dtype: int64

In [22]:
# Train a model (Random Forest in this example
X_resampled = np.array(X_resampled)
X_test = np.array(x_test)

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_resampled, y_resampled)

# Make predictions
y_pred = model.predict(x_test)

In [23]:
# Compute accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy * 100:.2f}%")

# Confusion matrix
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

# Classification report (Precision, Recall, F1-score)
print("Classification Report:\n", classification_report(y_test, y_pred))

Model Accuracy: 76.62%
Confusion Matrix:
 [[76 23]
 [13 42]]
Classification Report:
               precision    recall  f1-score   support

           0       0.85      0.77      0.81        99
           1       0.65      0.76      0.70        55

    accuracy                           0.77       154
   macro avg       0.75      0.77      0.75       154
weighted avg       0.78      0.77      0.77       154



In [24]:
# Create and train the Decision Tree classifier
model = DecisionTreeClassifier(random_state=42)
model.fit(x_train, y_train)

DecisionTreeClassifier(random_state=42)

In [25]:
y_pred = model.predict(x_test)

In [26]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy * 100:.2f}%")

Model Accuracy: 74.68%


In [27]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[75 24]
 [15 40]]
              precision    recall  f1-score   support

           0       0.83      0.76      0.79        99
           1       0.62      0.73      0.67        55

    accuracy                           0.75       154
   macro avg       0.73      0.74      0.73       154
weighted avg       0.76      0.75      0.75       154



In [28]:
model = LogisticRegression()
model.fit(x_train, y_train)

LogisticRegression()

In [29]:
y_pred = model.predict(x_test)

In [21]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy * 100:.2f}%")

Model Accuracy: 75.32%


In [23]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[79 20]
 [18 37]]
              precision    recall  f1-score   support

           0       0.81      0.80      0.81        99
           1       0.65      0.67      0.66        55

    accuracy                           0.75       154
   macro avg       0.73      0.74      0.73       154
weighted avg       0.76      0.75      0.75       154



In [24]:
from sklearn.metrics import roc_auc_score
auc_score = roc_auc_score(y_test, model.predict_proba(x_test)[:, 1])
print(f"ROC-AUC Score: {auc_score:.2f}")

ROC-AUC Score: 0.81


In [26]:
# Create and train the Random Forest classifier
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(x_train, y_train)

RandomForestClassifier(random_state=42)

In [27]:
y_pred = model.predict(x_test)

In [28]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy * 100:.2f}%")

Model Accuracy: 72.08%


In [29]:
print(confusion_matrix(y_test, y_pred))

[[77 22]
 [21 34]]


In [30]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.79      0.78      0.78        99
           1       0.61      0.62      0.61        55

    accuracy                           0.72       154
   macro avg       0.70      0.70      0.70       154
weighted avg       0.72      0.72      0.72       154



In [24]:
model=svm.SVC(kernel='linear')

In [25]:
model.fit(x_train,y_train)

SVC(kernel='linear')

In [27]:
y_pred=model.predict(x_test)

In [32]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.7532467532467533
[[79 20]
 [18 37]]
              precision    recall  f1-score   support

           0       0.81      0.80      0.81        99
           1       0.65      0.67      0.66        55

    accuracy                           0.75       154
   macro avg       0.73      0.74      0.73       154
weighted avg       0.76      0.75      0.75       154



In [30]:
pip install pickle

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement pickle (from versions: none)
ERROR: No matching distribution found for pickle

[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [31]:
import pickle
filename='diabetes_model.sav'
pickle.dump(model,open(filename,'wb'))